/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastcproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Göktuğ Güneş
 */
public class Guneskocyigitlevel2ekrani extends javax.swing.JFrame {
    DoubleLinkedList<Integer> mylist = new DoubleLinkedList<>();
    private String name ;
    String level = "level2";
    /**
     * Creates new form lvl2ekran
     */
     DNode<Integer> point  ;
    public Guneskocyigitlevel2ekrani(String name) {
        this.name = name ;
        method();
        point = mylist.head;
        initComponents();
    }
   
    
    private String getDiceFace(int roll) {
    String[] diceFaces = {
        "\u2680", "\u2681", "\u2682",
        "\u2683", "\u2684", "\u2685"
    };
    return diceFaces[roll];
}
    int dicetotal= 0 ;
    int totalpoint = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        dicebt = new javax.swing.JButton();
        piyon = new javax.swing.JLabel();
        diceLabel = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        pointlbl = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        infolbl = new javax.swing.JLabel();
        backlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 919));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel42.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("1");
        jLabel42.setPreferredSize(new java.awt.Dimension(26, 26));
        getContentPane().add(jLabel42);
        jLabel42.setBounds(419, 142, 26, 26);

        jLabel43.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("2");
        jLabel43.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel43);
        jLabel43.setBounds(480, 140, 34, 34);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("🟩");
        jLabel2.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 130, 42, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("🟩");
        jLabel1.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 130, 42, 42);

        jLabel44.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("3");
        jLabel44.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel44);
        jLabel44.setBounds(539, 140, 34, 34);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("🟩");
        jLabel3.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 130, 42, 42);

        jLabel46.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("5");
        jLabel46.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel46);
        jLabel46.setBounds(660, 140, 34, 34);

        jLabel48.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("7");
        jLabel48.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel48);
        jLabel48.setBounds(780, 140, 34, 34);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("🟩");
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 130, 42, 42);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("🟩");
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 130, 42, 42);

        jLabel50.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("9");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(899, 139, 21, 37);

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("🟩");
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(890, 130, 42, 42);

        jLabel45.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("4");
        jLabel45.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel45);
        jLabel45.setBounds(598, 140, 34, 34);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("🟩");
        jLabel7.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(590, 130, 42, 42);

        jLabel47.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("6");
        jLabel47.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel47);
        jLabel47.setBounds(719, 140, 34, 34);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("🟩");
        jLabel8.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(710, 130, 42, 42);

        jLabel51.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("10");
        jLabel51.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel51);
        jLabel51.setBounds(948, 136, 42, 42);

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("🟩");
        jLabel10.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(950, 130, 42, 42);

        jLabel49.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("8");
        jLabel49.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(jLabel49);
        jLabel49.setBounds(840, 140, 34, 34);

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("🟩");
        jLabel9.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(830, 130, 42, 42);

        jLabel11.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("START");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 140, 80, 30);

        jLabel52.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("11");
        jLabel52.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabel52);
        jLabel52.setBounds(1010, 138, 40, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 251, 0));
        jLabel12.setText("🟩");
        jLabel12.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1010, 130, 42, 42);

        jLabel53.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("12");
        jLabel53.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabel53);
        jLabel53.setBounds(1010, 198, 40, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("🟩");
        jLabel13.setPreferredSize(new java.awt.Dimension(42, 42));
        jLabel13.setRequestFocusEnabled(false);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1010, 190, 42, 42);

        jLabel54.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("13");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(1010, 260, 40, 35);

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 251, 0));
        jLabel14.setText("🟩");
        jLabel14.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1010, 250, 42, 42);

        jLabel55.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("14");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(950, 260, 40, 35);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("🟩");
        jLabel15.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(950, 250, 42, 42);

        jLabel56.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("15");
        getContentPane().add(jLabel56);
        jLabel56.setBounds(890, 260, 40, 35);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 251, 0));
        jLabel16.setText("🟩");
        jLabel16.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(890, 250, 42, 42);

        jLabel57.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("16");
        getContentPane().add(jLabel57);
        jLabel57.setBounds(829, 260, 40, 35);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 135, 0));
        jLabel17.setText("🟩");
        jLabel17.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(830, 250, 42, 42);

        jLabel58.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("17");
        getContentPane().add(jLabel58);
        jLabel58.setBounds(770, 260, 40, 35);

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 251, 0));
        jLabel18.setText("🟩");
        jLabel18.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(770, 250, 42, 42);

        jLabel59.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("18");
        getContentPane().add(jLabel59);
        jLabel59.setBounds(709, 260, 40, 35);

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("🟩");
        jLabel19.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(710, 250, 42, 42);

        jLabel60.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("19");
        getContentPane().add(jLabel60);
        jLabel60.setBounds(650, 260, 40, 35);

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 251, 0));
        jLabel20.setText("🟩");
        jLabel20.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(650, 250, 42, 42);

        jLabel61.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("20");
        getContentPane().add(jLabel61);
        jLabel61.setBounds(590, 260, 40, 35);

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("🟩");
        jLabel21.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(590, 250, 42, 42);

        jLabel62.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("21");
        getContentPane().add(jLabel62);
        jLabel62.setBounds(531, 260, 40, 35);

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 251, 0));
        jLabel22.setText("🟩");
        jLabel22.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(530, 250, 42, 42);

        jLabel63.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("22");
        getContentPane().add(jLabel63);
        jLabel63.setBounds(470, 260, 40, 35);

        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 0));
        jLabel23.setText("🟩");
        jLabel23.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(470, 250, 42, 42);

        jLabel64.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("23");
        getContentPane().add(jLabel64);
        jLabel64.setBounds(410, 260, 40, 35);

        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 251, 0));
        jLabel24.setText("🟩");
        jLabel24.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel24);
        jLabel24.setBounds(410, 250, 42, 42);

        jLabel65.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("24");
        getContentPane().add(jLabel65);
        jLabel65.setBounds(410, 320, 40, 35);

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("🟩");
        jLabel25.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel25);
        jLabel25.setBounds(410, 310, 42, 42);

        jLabel66.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("25");
        getContentPane().add(jLabel66);
        jLabel66.setBounds(410, 380, 40, 35);

        jLabel67.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("26");
        getContentPane().add(jLabel67);
        jLabel67.setBounds(470, 380, 40, 35);

        jLabel26.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 251, 0));
        jLabel26.setText("🟩");
        jLabel26.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel26);
        jLabel26.setBounds(410, 370, 42, 42);

        jLabel27.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("🟩");
        jLabel27.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(470, 370, 42, 42);

        jLabel68.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("27");
        getContentPane().add(jLabel68);
        jLabel68.setBounds(530, 380, 40, 35);

        jLabel28.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 251, 0));
        jLabel28.setText("🟩");
        jLabel28.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(530, 370, 42, 42);

        jLabel69.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("28");
        getContentPane().add(jLabel69);
        jLabel69.setBounds(590, 380, 40, 35);

        jLabel29.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 153, 0));
        jLabel29.setText("🟩");
        jLabel29.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(590, 370, 42, 42);

        jLabel70.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("29");
        getContentPane().add(jLabel70);
        jLabel70.setBounds(650, 380, 40, 35);

        jLabel30.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 251, 0));
        jLabel30.setText("🟩");
        jLabel30.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(650, 370, 42, 42);

        jLabel71.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("30");
        getContentPane().add(jLabel71);
        jLabel71.setBounds(710, 380, 40, 35);

        jLabel31.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 153, 0));
        jLabel31.setText("🟩");
        jLabel31.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel31);
        jLabel31.setBounds(710, 370, 42, 42);

        jLabel72.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("31");
        getContentPane().add(jLabel72);
        jLabel72.setBounds(770, 380, 40, 35);

        jLabel32.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 251, 0));
        jLabel32.setText("🟩");
        jLabel32.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel32);
        jLabel32.setBounds(770, 370, 42, 42);

        jLabel73.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("32");
        getContentPane().add(jLabel73);
        jLabel73.setBounds(830, 380, 40, 35);

        jLabel33.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 153, 0));
        jLabel33.setText("🟩");
        jLabel33.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel33);
        jLabel33.setBounds(830, 370, 42, 42);

        jLabel74.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("33");
        getContentPane().add(jLabel74);
        jLabel74.setBounds(890, 380, 40, 35);

        jLabel34.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 251, 0));
        jLabel34.setText("🟩");
        jLabel34.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel34);
        jLabel34.setBounds(890, 370, 42, 42);

        jLabel75.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("34");
        getContentPane().add(jLabel75);
        jLabel75.setBounds(950, 380, 40, 35);

        jLabel35.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 153, 0));
        jLabel35.setText("🟩");
        jLabel35.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel35);
        jLabel35.setBounds(950, 370, 42, 42);

        jLabel76.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("35");
        getContentPane().add(jLabel76);
        jLabel76.setBounds(1010, 380, 40, 35);

        jLabel36.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 251, 0));
        jLabel36.setText("🟩");
        jLabel36.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1010, 370, 42, 42);

        jLabel77.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("36");
        getContentPane().add(jLabel77);
        jLabel77.setBounds(1010, 440, 40, 35);

        jLabel37.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 153, 0));
        jLabel37.setText("🟩");
        jLabel37.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel37);
        jLabel37.setBounds(1010, 430, 42, 42);

        jLabel78.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("37");
        jLabel78.setToolTipText("");
        getContentPane().add(jLabel78);
        jLabel78.setBounds(1010, 500, 40, 35);

        jLabel38.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 251, 0));
        jLabel38.setText("🟩");
        jLabel38.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1010, 490, 42, 42);

        jLabel79.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("38");
        getContentPane().add(jLabel79);
        jLabel79.setBounds(950, 500, 40, 35);

        jLabel39.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 153, 0));
        jLabel39.setText("🟩");
        jLabel39.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel39);
        jLabel39.setBounds(950, 490, 42, 42);

        jLabel80.setFont(new java.awt.Font("Stencil", 0, 34)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("39");
        getContentPane().add(jLabel80);
        jLabel80.setBounds(890, 500, 40, 35);

        jLabel40.setFont(new java.awt.Font("Segoe UI Symbol", 0, 40)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 251, 0));
        jLabel40.setText("🟩");
        jLabel40.setPreferredSize(new java.awt.Dimension(42, 42));
        getContentPane().add(jLabel40);
        jLabel40.setBounds(890, 490, 42, 42);

        jLabel41.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("FINISH");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(791, 500, 90, 30);

        dicebt.setBackground(new java.awt.Color(204, 0, 0));
        dicebt.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        dicebt.setForeground(new java.awt.Color(255, 255, 255));
        dicebt.setText("DICE");
        dicebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicebtActionPerformed(evt);
            }
        });
        getContentPane().add(dicebt);
        dicebt.setBounds(190, 650, 180, 32);

        piyon.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        piyon.setForeground(new java.awt.Color(204, 0, 0));
        piyon.setText("♙");
        piyon.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(piyon);
        piyon.setBounds(350, 100, 32, 32);

        diceLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 150)); // NOI18N
        diceLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        getContentPane().add(diceLabel);
        diceLabel.setBounds(220, 490, 140, 130);

        jLabel81.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel81.setText("TOTAL POINT");
        getContentPane().add(jLabel81);
        jLabel81.setBounds(200, 260, 160, 25);

        pointlbl.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        pointlbl.setForeground(new java.awt.Color(255, 255, 255));
        pointlbl.setText("0");
        getContentPane().add(pointlbl);
        pointlbl.setBounds(260, 300, 110, 25);

        jLabel83.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("CHEST INFORMATION: ");
        getContentPane().add(jLabel83);
        jLabel83.setBounds(660, 650, 260, 25);

        infolbl.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        infolbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(infolbl);
        infolbl.setBounds(920, 645, 400, 30);

        backlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/blue-neon-frame-dark-background_53876-113902.jpg"))); // NOI18N
        getContentPane().add(backlabel);
        backlabel.setBounds(0, 0, 1380, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dicebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicebtActionPerformed
        // TODO add your handling code here:
        dicebt.setEnabled(false); 

Timer timer = new Timer(100, null); 
final int[] counter = {0};

timer.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        if (counter[0] < 10) {
            int roll = (int)(Math.random() * 6);
            diceLabel.setText(getDiceFace(roll));
            counter[0]++;
        } else {
            timer.stop();
            int finalRoll = (int)(Math.random() * 6) + 1; 
            diceLabel.setText(getDiceFace(finalRoll - 1));
            System.out.println("Atılan zar: " + finalRoll);
            point = mylist.meth2(point, finalRoll);
            DNode ens = mylist.head;
            
           for (int i = 0 ; i <40 ;i++){
               System.out.print(ens.data+" ");
              
               if(ens.next == null){
                   break ;
               }
                ens =  ens.next ;
           }
if (point == null) {
    System.out.println("Hata: point null değer aldı!");
    dicebt.setEnabled(true);
    return;
}
            dicetotal += finalRoll;
            System.out.println(" İlk gidilen kutu: " + dicetotal);
           
            

            int num = (Integer)point.data ;
            switch (num) {
            
                case 0: totalpoint = totalpoint - 5 ;
                infolbl.setText("-5 Points");
                    break;
            
                case 1://boş sandık
                    infolbl.setText("Empty Chest");
                    break;
           
                case 2:totalpoint += 10 ;
                infolbl.setText("+10 Points");
                    break;
                default:
                    break;
            }
            pointlbl.setText(String.valueOf(totalpoint));
             updatePiyonLocation(dicetotal);
          //  gecikme 
            new Timer(1000, new ActionListener() {
                public void actionPerformed(ActionEvent evt2) {
                    switch(num){
                    case 3: mylist.meth2(point, -4);
                    infolbl.setText("Go 4 steps back");
                dicetotal = dicetotal -4 ;
                    break;
            
                case 4:mylist.meth2(point, 4);
                infolbl.setText("4 steps front");
                dicetotal = dicetotal +4 ;
                    break;
           
                case 5: mylist.meth2(point, -2);
                infolbl.setText("2 steps back");
                dicetotal = dicetotal -2 ;
                    break;
                default:
                    break;
                    }                                                
                        if (dicetotal <= 0) {
                            dicetotal = 0;
                            piyon.setLocation(350, 100);
                        } else {
                            updatePiyonLocation(dicetotal);
                        }
                    
                    dicebt.setEnabled(true); 
                    ((Timer)evt2.getSource()).stop();
                    if(dicetotal> 39){
        piyon.setLocation(815,470);
         dicebt.setEnabled(false);
        dicebt.setText("GAME OVER");
            try {
                save(name,level, totalpoint);
                /*Puanı kaydetme kod blokları gelecek*/
            } catch (IOException ex) {
                Logger.getLogger(Guneskocyigitlevel2ekrani.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
            JOptionPane.showMessageDialog(rootPane, "Your point: "+ totalpoint);
                setVisible(false);
                Guneskocyigitmain ekr = new Guneskocyigitmain();
                ekr.setVisible(true);
            
            
        
    }
                }
            }).start();
        }
    }
        });
timer.start();

       
    }//GEN-LAST:event_dicebtActionPerformed

    
       void method(){
    DNode<Integer> startpoint = new DNode<>(null);
    mylist.Nadd(startpoint);  // head = startpoint

    DNode<Integer> temp = mylist.head;  // head üzerinden zincire bağlan
    for(int i = 1 ; i < 40 ; i++){
        int rndm = (int)(Math.random() * 6);
        DNode<Integer> newNode = new DNode<>(rndm);
        temp.next = newNode;
        newNode.prev = temp;
        temp = newNode;
    }

    mylist.tail = temp; // tail'i de en son node yap

    point = mylist.head; // point başlangıçta head'i göstersin
}

        private void updatePiyonLocation(int position){
        switch(dicetotal){
        case 1: piyon.setLocation(415, 105);
        break;
        case 2: piyon.setLocation(475, 105);
        break;
        case 3: piyon.setLocation(535,105);
        break;
        case 4: piyon.setLocation(595,105);
        break;
        case 5: piyon.setLocation(655,105);
        break;
        case 6: piyon.setLocation(715,105);
        break;
        case 7: piyon.setLocation(775,105);
        break;
        case 8: piyon.setLocation(835,105);
        break;
        case 9: piyon.setLocation(895,105);
        break;
        case 10: piyon.setLocation(955,105);
        break;
        case 11: piyon.setLocation(1015,105);
        break;
        case 12: piyon.setLocation(1045,195);
        break;
         case 13: piyon.setLocation(1045,255);
        break;
         case 14: piyon.setLocation(955,225);
        break;
         case 15: piyon.setLocation(895,225);
        break;
         case 16: piyon.setLocation(835,225);
        break;
         case 17: piyon.setLocation(775,225);
        break;
         case 18: piyon.setLocation(715,225);
        break;
         case 19: piyon.setLocation(655,225);
        break;
         case 20: piyon.setLocation(595,225);
        break;
         case 21: piyon.setLocation(535,225);
        break;
         case 22: piyon.setLocation(475,225);
        break;
        case 23: piyon.setLocation(415,225);
        break;
        case 24: piyon.setLocation(385,315);
        break;
        case 25: piyon.setLocation(385,375);
        break;
        case 26: piyon.setLocation(475,345);
        break;
        case 27: piyon.setLocation(535,345);
        break;
        case 28: piyon.setLocation(595,345);
        break;
        case 29: piyon.setLocation(655,345);
        break;
        case 30: piyon.setLocation(715,345);
        break;
        case 31: piyon.setLocation(775,345);
        break;
        case 32: piyon.setLocation(835,345);
        break;
        case 33: piyon.setLocation(895,345);
        break;
        case 34: piyon.setLocation(955,345);
        break;
        case 35: piyon.setLocation(1015,345);
        break;
        case 36: piyon.setLocation(1045,435);
        break;
        case 37: piyon.setLocation(1045,495);
        break;
        case 38: piyon.setLocation(955,465);
        break;
        case 39: piyon.setLocation(895,465);
        break;
    }
        }
        
        
         void save(String username,String level, int score) throws IOException{   
    File file = new File("score.txt");
             if(!file.exists()) {
        file.createNewFile();
    }
    FileWriter fwriter = new FileWriter(file, true); 
    BufferedWriter bWriter = new BufferedWriter(fwriter);
    bWriter.write(username + ", " +level + ", " + score); 
    bWriter.newLine(); 
    bWriter.close();
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guneskocyigitlevel2ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guneskocyigitlevel2ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guneskocyigitlevel2ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guneskocyigitlevel2ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guneskocyigitlevel2ekrani("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlabel;
    private javax.swing.JLabel diceLabel;
    private javax.swing.JButton dicebt;
    private javax.swing.JLabel infolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel piyon;
    private javax.swing.JLabel pointlbl;
    // End of variables declaration//GEN-END:variables
}
