/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastcproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author Göktuğ Güneş
 */
public class lvl1ekran extends javax.swing.JFrame {
    private String name ;
    String level = "level1";
    /**
     * Creates new form lvl1ekran
     */
   private static LinkedList<Integer> liste = new LinkedList<>();
     
     
     
         public lvl1ekran(String name){
         this.name = name ;
        initComponents(); 
         method();
         point = liste.head;
         }
    
    Node<Integer> point = liste.head ;
     
   
   private String getDiceFace(int roll) {
    String[] diceFaces = {
        "\u2680", "\u2681", "\u2682",
        "\u2683", "\u2684", "\u2685"
    };
    return diceFaces[roll];
}
   int dicetotal= 0 ;
   
   int totalpoint = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sq2 = new javax.swing.JLabel();
        sq1 = new javax.swing.JLabel();
        sq5 = new javax.swing.JLabel();
        sq4 = new javax.swing.JLabel();
        sq3 = new javax.swing.JLabel();
        sq8 = new javax.swing.JLabel();
        sq7 = new javax.swing.JLabel();
        sq6 = new javax.swing.JLabel();
        sq9 = new javax.swing.JLabel();
        sq10 = new javax.swing.JLabel();
        sq11 = new javax.swing.JLabel();
        sq12 = new javax.swing.JLabel();
        sq13 = new javax.swing.JLabel();
        sq14 = new javax.swing.JLabel();
        sq15 = new javax.swing.JLabel();
        sq16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sq17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sq18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sq19 = new javax.swing.JLabel();
        sq20 = new javax.swing.JLabel();
        sq21 = new javax.swing.JLabel();
        sq23 = new javax.swing.JLabel();
        sq22 = new javax.swing.JLabel();
        sq24 = new javax.swing.JLabel();
        sq26 = new javax.swing.JLabel();
        sq25 = new javax.swing.JLabel();
        sq27 = new javax.swing.JLabel();
        sq28 = new javax.swing.JLabel();
        sq29 = new javax.swing.JLabel();
        sq30 = new javax.swing.JLabel();
        sq31 = new javax.swing.JLabel();
        sq32 = new javax.swing.JLabel();
        sq33 = new javax.swing.JLabel();
        startlabel = new javax.swing.JLabel();
        finishlabel = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dicebt = new javax.swing.JButton();
        diceLabel = new javax.swing.JLabel();
        piyon = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        pointlbl = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        infolbl = new javax.swing.JLabel();
        backlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        sq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq2.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq2);
        sq2.setBounds(530, 150, 33, 33);

        sq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq1.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq1);
        sq1.setBounds(480, 150, 33, 33);

        sq5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq5.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq5);
        sq5.setBounds(680, 150, 33, 33);

        sq4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq4.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq4);
        sq4.setBounds(630, 150, 33, 33);

        sq3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq3.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq3);
        sq3.setBounds(580, 150, 33, 33);

        sq8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq8.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq8);
        sq8.setBounds(830, 150, 33, 33);

        sq7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq7.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq7);
        sq7.setBounds(780, 150, 33, 33);

        sq6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq6.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq6);
        sq6.setBounds(730, 150, 33, 33);

        sq9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq9.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq9);
        sq9.setBounds(880, 150, 33, 33);

        sq10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq10.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq10);
        sq10.setBounds(880, 200, 33, 33);

        sq11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq11.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq11);
        sq11.setBounds(880, 250, 33, 33);

        sq12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq12.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq12);
        sq12.setBounds(830, 250, 33, 33);

        sq13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq13.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq13);
        sq13.setBounds(780, 250, 33, 33);

        sq14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq14.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq14);
        sq14.setBounds(730, 250, 33, 33);

        sq15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq15.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq15);
        sq15.setBounds(680, 250, 33, 33);

        sq16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq16.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq16);
        sq16.setBounds(630, 250, 33, 33);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(630, 250, 33, 33);

        sq17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq17.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq17);
        sq17.setBounds(580, 250, 33, 33);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(580, 250, 33, 33);

        sq18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq18.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq18);
        sq18.setBounds(530, 250, 33, 33);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(530, 250, 33, 33);

        sq19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq19.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq19);
        sq19.setBounds(480, 250, 33, 33);

        sq20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq20.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq20);
        sq20.setBounds(480, 300, 33, 33);

        sq21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq21.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq21);
        sq21.setBounds(480, 350, 33, 33);

        sq23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq23.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq23);
        sq23.setBounds(580, 350, 33, 33);

        sq22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq22.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq22);
        sq22.setBounds(530, 350, 33, 33);

        sq24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq24.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq24);
        sq24.setBounds(630, 350, 33, 33);

        sq26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq26.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq26);
        sq26.setBounds(730, 350, 33, 33);

        sq25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq25.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq25);
        sq25.setBounds(680, 350, 33, 33);

        sq27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq27.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq27);
        sq27.setBounds(780, 350, 33, 33);

        sq28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq28.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq28);
        sq28.setBounds(830, 350, 33, 33);

        sq29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq29.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq29);
        sq29.setBounds(880, 350, 33, 33);

        sq30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq30.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq30);
        sq30.setBounds(880, 400, 33, 33);

        sq31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq31.setText("jLabel35");
        sq31.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq31);
        sq31.setBounds(880, 450, 33, 33);

        sq32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32.png"))); // NOI18N
        sq32.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq32);
        sq32.setBounds(830, 450, 33, 33);

        sq33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/square-outline-32 (1).png"))); // NOI18N
        sq33.setPreferredSize(new java.awt.Dimension(33, 33));
        getContentPane().add(sq33);
        sq33.setBounds(780, 450, 33, 33);

        startlabel.setFont(new java.awt.Font("Stencil", 2, 18)); // NOI18N
        startlabel.setForeground(new java.awt.Color(255, 255, 255));
        startlabel.setText("START");
        getContentPane().add(startlabel);
        startlabel.setBounds(410, 160, 60, 19);

        finishlabel.setFont(new java.awt.Font("Stencil", 2, 18)); // NOI18N
        finishlabel.setForeground(new java.awt.Color(255, 255, 255));
        finishlabel.setText("FINISH");
        getContentPane().add(finishlabel);
        finishlabel.setBounds(700, 450, 70, 40);

        l1.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("1");
        getContentPane().add(l1);
        l1.setBounds(490, 158, 12, 21);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 158, 12, 21);

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 158, 12, 21);

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("4");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 158, 12, 21);

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("5");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 158, 12, 21);

        jLabel5.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("6");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 158, 12, 21);

        jLabel6.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("7");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(790, 158, 12, 21);

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("8");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 158, 12, 21);

        jLabel8.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("9");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(890, 158, 12, 21);

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("10");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(884, 208, 24, 21);

        jLabel10.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("11");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(884, 258, 24, 21);

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("12");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(834, 258, 24, 21);

        jLabel12.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("13");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(784, 258, 24, 21);

        jLabel13.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("14");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(734, 258, 24, 21);

        jLabel14.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("15");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(684, 258, 24, 21);

        jLabel15.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("16");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(634, 258, 24, 21);

        jLabel16.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("17");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(584, 258, 24, 21);

        jLabel17.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("18");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(534, 258, 24, 21);

        jLabel19.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(484, 258, 24, 21);

        jLabel21.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("20");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(484, 308, 24, 21);

        jLabel23.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("21");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(484, 358, 24, 21);

        jLabel24.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("22");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(534, 358, 24, 21);

        jLabel25.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("23");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(584, 358, 24, 21);

        jLabel26.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("24");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(634, 358, 24, 21);

        jLabel27.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("25");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(684, 358, 24, 21);

        jLabel28.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("26");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(734, 358, 24, 21);

        jLabel29.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("27");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(784, 358, 24, 21);

        jLabel30.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("28");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(834, 358, 24, 21);

        jLabel31.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("29");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(884, 358, 24, 21);

        jLabel32.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("30");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(884, 408, 24, 21);

        jLabel33.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("31");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(884, 458, 24, 21);

        jLabel34.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("32");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(834, 458, 24, 21);

        jLabel35.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("33");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(784, 458, 24, 21);

        dicebt.setBackground(new java.awt.Color(204, 0, 0));
        dicebt.setFont(new java.awt.Font("Stencil", 0, 17)); // NOI18N
        dicebt.setForeground(new java.awt.Color(255, 255, 255));
        dicebt.setText("DICE");
        dicebt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        dicebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dicebtActionPerformed(evt);
            }
        });
        getContentPane().add(dicebt);
        dicebt.setBounds(1060, 480, 100, 28);

        diceLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 100)); // NOI18N
        diceLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(diceLabel);
        diceLabel.setBounds(1070, 340, 90, 100);

        piyon.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        piyon.setForeground(new java.awt.Color(255, 255, 255));
        piyon.setText("♙");
        getContentPane().add(piyon);
        piyon.setBounds(430, 130, 24, 20);

        jLabel36.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("TOTAL POINT:");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(570, 50, 170, 40);

        pointlbl.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        pointlbl.setForeground(new java.awt.Color(255, 255, 255));
        pointlbl.setText("0");
        getContentPane().add(pointlbl);
        pointlbl.setBounds(730, 60, 70, 25);

        jLabel38.setFont(new java.awt.Font("Stencil", 2, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 0));
        jLabel38.setText("BOX INFORMATION");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(260, 440, 170, 19);

        infolbl.setFont(new java.awt.Font("Stencil", 2, 14)); // NOI18N
        infolbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(infolbl);
        infolbl.setBounds(260, 470, 160, 20);

        backlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/datastcproject/neon-gaming-background_23-2151932065.jpg"))); // NOI18N
        backlabel.setPreferredSize(new java.awt.Dimension(1380, 700));
        getContentPane().add(backlabel);
        backlabel.setBounds(0, 0, 1380, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dicebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dicebtActionPerformed
     dicebt.setEnabled(false); 

Timer timer = new Timer(100, null); 
final int[] counter = {0}; // sayaç

timer.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        if (counter[0] < 10) { 
            int roll = (int)(Math.random() * 6); 
            diceLabel.setText(getDiceFace(roll)); 
            counter[0]++;
            
        } else {
            timer.stop();
            int finalRoll = (int)(Math.random() * 6);
            diceLabel.setText(getDiceFace(finalRoll));
            System.out.println("Atılan zar: " + (finalRoll + 1));
            dicebt.setEnabled(true); 
            dicetotal += finalRoll + 1;
            point = liste.meth(point, finalRoll+1);
            
            
              switch(dicetotal){
        case 1: piyon.setLocation(484, 130);
        break;
        case 2: piyon.setLocation(534, 130);
        break;
        case 3: piyon.setLocation(584, 130);
        break;
        case 4: piyon.setLocation(634, 130);
        break;
        case 5: piyon.setLocation(684, 130);
        break;
        case 6: piyon.setLocation(734, 130);
        break;
        case 7: piyon.setLocation(784, 130);
        break;
        case 8: piyon.setLocation(834, 130);
        break;
        case 9: piyon.setLocation(884, 130);
        break;
        case 10: piyon.setLocation(910, 203);
        break;
        case 11: piyon.setLocation(910, 253);
        break;
        case 12: piyon.setLocation(834, 230);
        break;
         case 13: piyon.setLocation(784, 230);
        break;
         case 14: piyon.setLocation(734, 230);
        break;
         case 15: piyon.setLocation(684, 230);
        break;
         case 16: piyon.setLocation(634, 230);
        break;
         case 17: piyon.setLocation(584, 230);
        break;
         case 18: piyon.setLocation(534, 230);
        break;
         case 19: piyon.setLocation(484, 230);
        break;
         case 20: piyon.setLocation(460, 304);
        break;
         case 21: piyon.setLocation(460, 354);
        break;
         case 22: piyon.setLocation(534, 330);
        break;
        case 23: piyon.setLocation(584, 330);
        break;
        case 24: piyon.setLocation(634, 330);
        break;
        case 25: piyon.setLocation(684, 330);
        break;
        case 26: piyon.setLocation(734, 330);
        break;
        case 27: piyon.setLocation(784, 330);
        break;
        case 28: piyon.setLocation(834, 330);
        break;
        case 29: piyon.setLocation(884, 330);
        break;
        case 30: piyon.setLocation(910, 404);
        break;
        case 31: piyon.setLocation(910, 454);
        break;
        case 32: piyon.setLocation(834, 430);
        break;
        case 33: piyon.setLocation(784, 430);
        break;
    }if(dicetotal > 33){
        piyon.setLocation(724, 430);
        dicebt.setEnabled(false);
        dicebt.setText("GAME OVER");
                try {
                    save(name, level,totalpoint);
                    
                } catch (IOException ex) {
                    Logger.getLogger(lvl1ekran.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        int answer = JOptionPane.showConfirmDialog(null, "YOUR POINT: "+ totalpoint + "  Do you want to continue?", "Question", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
    /* BİR SONRAKİ OYUN BAŞLAYACK AYNI İSİM ÜZERİNE*/
    dicetotal = 0 ;
    totalpoint = 0;
    piyon.setLocation(430,130);
    pointlbl.setText("0");
            infolbl.setText("");
            dicebt.setEnabled(true);
            dicebt.setText("DICE");
            setVisible(false);
            Guneskocyigitlevel2ekrani ekran = new Guneskocyigitlevel2ekrani(name);
            ekran.setVisible(true);
} else if (answer == JOptionPane.NO_OPTION) {
    dicetotal = 0 ;
    totalpoint = 0;
    piyon.setLocation(430,130);
            setVisible(false);
            Guneskocyigitmain grş = new Guneskocyigitmain();
            grş.setVisible(true);
            pointlbl.setText("0");
            infolbl.setText("");
            dicebt.setEnabled(true);
            dicebt.setText("DICE");
    
}
    }
            System.out.println("total dice: " +dicetotal);
            
            System.out.println("All List: ");
            for(int i =1 ; i < 34 ; i++){
                System.out.print(liste.find(i)+" ");
             }   
            System.out.println("");
            if(liste.find(dicetotal) == 0){
        totalpoint -= 5 ;
        infolbl.setText("-5 POINTS :( ");
        pointlbl.setText(Integer.toString(totalpoint));
        }else if(liste.find(dicetotal) == 1){
        infolbl.setText("EMPTY CHEST ");
        }else if(liste.find(dicetotal) == 2){
        totalpoint += 10 ;
        infolbl.setText("+10 POINTS :) ");
        pointlbl.setText(Integer.toString(totalpoint));
        }
            
        }
        //System.out.println(point.data);
    }
        });
timer.start();
      
 


 
    
    }//GEN-LAST:event_dicebtActionPerformed
 void method() {
    Node<Integer> head = new Node<>(null);
    liste.add(head);

    Node<Integer> temp = head;
    for (int i = 1; i < 34; i++) {
        int randomNumber = (int)(Math.random() * 3);
        Node<Integer> newNode = new Node<>(randomNumber);
        temp.next = newNode;  
        temp = newNode;       
    }
}
 
 void save(String username,String level, int score) throws IOException{   
    File file = new File("score.txt");
    if(!file.exists()) {
        file.createNewFile();
    }
    FileWriter fwriter = new FileWriter(file, true); 
    BufferedWriter bWriter = new BufferedWriter(fwriter);
    bWriter.write(username + ", "+level+", " + score);
    bWriter.newLine(); 
    bWriter.close();
 }
 

    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lvl1ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lvl1ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lvl1ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lvl1ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
                    
                    
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lvl1ekran("").setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlabel;
    private javax.swing.JLabel diceLabel;
    private javax.swing.JButton dicebt;
    private javax.swing.JLabel finishlabel;
    private javax.swing.JLabel infolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel piyon;
    private javax.swing.JLabel pointlbl;
    private javax.swing.JLabel sq1;
    private javax.swing.JLabel sq10;
    private javax.swing.JLabel sq11;
    private javax.swing.JLabel sq12;
    private javax.swing.JLabel sq13;
    private javax.swing.JLabel sq14;
    private javax.swing.JLabel sq15;
    private javax.swing.JLabel sq16;
    private javax.swing.JLabel sq17;
    private javax.swing.JLabel sq18;
    private javax.swing.JLabel sq19;
    private javax.swing.JLabel sq2;
    private javax.swing.JLabel sq20;
    private javax.swing.JLabel sq21;
    private javax.swing.JLabel sq22;
    private javax.swing.JLabel sq23;
    private javax.swing.JLabel sq24;
    private javax.swing.JLabel sq25;
    private javax.swing.JLabel sq26;
    private javax.swing.JLabel sq27;
    private javax.swing.JLabel sq28;
    private javax.swing.JLabel sq29;
    private javax.swing.JLabel sq3;
    private javax.swing.JLabel sq30;
    private javax.swing.JLabel sq31;
    private javax.swing.JLabel sq32;
    private javax.swing.JLabel sq33;
    private javax.swing.JLabel sq4;
    private javax.swing.JLabel sq5;
    private javax.swing.JLabel sq6;
    private javax.swing.JLabel sq7;
    private javax.swing.JLabel sq8;
    private javax.swing.JLabel sq9;
    private javax.swing.JLabel startlabel;
    // End of variables declaration//GEN-END:variables
}
